---
title: "Part 3 Solutions"
---

## Exercise 1

```{r}
library(epiworldR)

# Initialize model
model_seirconn <- ModelSEIRCONN(
  name              = "Flu",
  n                 = 10000, 
  prevalence        = 0.01, 
  contact_rate      = 2,
  prob_transmission = 0.5,
  incubation_days   = 2,
  prob_recovery     = 1/7
)

# Generating a saver
saver <- make_saver("reproductive")

# Running and printing
run_multiple(model_seirconn, ndays = 20, nsims = 100, saver = saver, nthread = 2)

# Plotting
seirconn_100_r <- run_multiple_get_results(model_seirconn)$reproductive
plot(seirconn_100_r)
```

## Exercise 2

```{r}
# Initialize Model
model_seirconn <- ModelSEIRCONN(
  name              = "Flu",
  n                 = 10000, 
  prevalence        = 0.01, 
  contact_rate      = 2,
  prob_transmission = 0.5,
  incubation_days   = 2,
  prob_recovery     = 1/7
)

# Creating a tool
epitool <- tool(
  name = "Vaccine",
  susceptibility_reduction = .9,
  transmission_reduction = .5,
  recovery_enhancer = .5, 
  death_reduction = .9
)

# Adding a global action
vaccine_day_10 <- globalaction_tool(epitool, prob = .5, day = 10)
add_global_action(model_seirconn, vaccine_day_10)

# Generating a saver
saver <- make_saver("reproductive")
# Running the model
run_multiple(model_seirconn, ndays = 20, nsims = 100, saver = saver, 
             nthread = 2)

# Plotting
seirconn_100_r2 <- run_multiple_get_results(model_seirconn)$reproductive
plot(seirconn_100_r2)
```
